% format_in.pl: DCG rules for very common and tedious things
% This file is from Chemlogic, a logic programming computer chemistry system
% <http://icebergsystems.ca/chemlogic>
% (C) Copyright 2012-2015 Nicholas Paun


%%%% THIS FILE IS AUTOMATICALLY GENERATED %%%%

num_decimal(10) --> "10".
num_decimal(11) --> "11".
num_decimal(12) --> "12".
num_decimal(13) --> "13".
num_decimal(14) --> "14".
num_decimal(15) --> "15".
num_decimal(16) --> "16".
num_decimal(17) --> "17".
num_decimal(18) --> "18".
num_decimal(19) --> "19".

num_decimal(20) --> "20".
num_decimal(21) --> "21".
num_decimal(22) --> "22".
num_decimal(23) --> "23".
num_decimal(24) --> "24".
num_decimal(25) --> "25".
num_decimal(26) --> "26".
num_decimal(27) --> "27".
num_decimal(28) --> "28".
num_decimal(29) --> "29".

num_decimal(30) --> "30".
num_decimal(31) --> "31".
num_decimal(32) --> "32".
num_decimal(33) --> "33".
num_decimal(34) --> "34".
num_decimal(35) --> "35".
num_decimal(36) --> "36".
num_decimal(37) --> "37".
num_decimal(38) --> "38".
num_decimal(39) --> "39".

num_decimal(40) --> "40".
num_decimal(41) --> "41".
num_decimal(42) --> "42".
num_decimal(43) --> "43".
num_decimal(44) --> "44".
num_decimal(45) --> "45".
num_decimal(46) --> "46".
num_decimal(47) --> "47".
num_decimal(48) --> "48".
num_decimal(49) --> "49".

num_decimal(50) --> "50".
num_decimal(51) --> "51".
num_decimal(52) --> "52".
num_decimal(53) --> "53".
num_decimal(54) --> "54".
num_decimal(55) --> "55".
num_decimal(56) --> "56".
num_decimal(57) --> "57".
num_decimal(58) --> "58".
num_decimal(59) --> "59".

num_decimal(60) --> "60".
num_decimal(61) --> "61".
num_decimal(62) --> "62".
num_decimal(63) --> "63".
num_decimal(64) --> "64".
num_decimal(65) --> "65".
num_decimal(66) --> "66".
num_decimal(67) --> "67".
num_decimal(68) --> "68".
num_decimal(69) --> "69".

num_decimal(70) --> "70".
num_decimal(71) --> "71".
num_decimal(72) --> "72".
num_decimal(73) --> "73".
num_decimal(74) --> "74".
num_decimal(75) --> "75".
num_decimal(76) --> "76".
num_decimal(77) --> "77".
num_decimal(78) --> "78".
num_decimal(79) --> "79".

num_decimal(80) --> "80".
num_decimal(81) --> "81".
num_decimal(82) --> "82".
num_decimal(83) --> "83".
num_decimal(84) --> "84".
num_decimal(85) --> "85".
num_decimal(86) --> "86".
num_decimal(87) --> "87".
num_decimal(88) --> "88".
num_decimal(89) --> "89".

num_decimal(90) --> "90".
num_decimal(91) --> "91".
num_decimal(92) --> "92".
num_decimal(93) --> "93".
num_decimal(94) --> "94".
num_decimal(95) --> "95".
num_decimal(96) --> "96".
num_decimal(97) --> "97".
num_decimal(98) --> "98".
num_decimal(99) --> "99".


num_decimal(2) --> "2".
num_decimal(3) --> "3".
num_decimal(4) --> "4".
num_decimal(5) --> "5".
num_decimal(6) --> "6".
num_decimal(7) --> "7".
num_decimal(8) --> "8".
num_decimal(9) --> "9".
