#!/bin/sh

TOPLEVEL=`git rev-parse --show-toplevel`
CTAGS=/usr/local/bin/exctags

if [ ! -e $CTAGS ]; then
	exit
fi

cd $TOPLEVEL
$CTAGS \
	--langdef=Prolog \
	--langmap=Prolog:.pl \
       	--regex-Prolog='/^([a-z0-9_:]{2,})/\1/p,predicate,predicate definition/' \
	--exclude="docs/*" \
	--extra=f \
	-R .

sed -i '' -E  '/(cl|cl_poly|common|retained)	/d' tags #Suppress useless procedures.

